#!/bin/sh -x

PKG=xsede-oauth-mapfile
VER=$(cat VERSION)
REL=$(cat RELEASE)
RPMDIR="/home/vagrant/rpmbuild/RPMS/noarch/"
RPMFILE=$RPMDIR/$PKG-$VER-$REL.noarch.rpm
export VER
export REL
echo $RPMFILE

if [ ! -e VERSION ]; then
  echo "You may not be in the right place to run upload"
  echo "Please run from the root of the package"
  exit 1
fi

rpmbuild --target noarch -bb $PKG.spec

