#!/bin/sh -x

PKG=xsede-oauth-mapfile
VER=$(cat VERSION)
REL=$(cat RELEASE)

if [ ! -e VERSION ]; then
  echo "You may not be in the right place to run upload"
  echo "Please run from the root of the package"
  exit 1
fi


REPO=software.xsede.org
#REPO=localhost

REPO_SOFTWARE=/local/software.xsede.org/development/$PKG
REPO_SUBDIR=$PKG-$VER-$REL

tar cvfz $REPO_SUBDIR.tgz INSTALL LICENSE.txt mapfileupdate.sh README.md README-xsede-user-mapfile xsede-user-mapfile-config-template.json xsede-user-mapfile.py

ssh -l xsedesig  $REPO "mkdir -p $REPO_SOFTWARE/$REPO_SUBDIR"

scp -p $PKG-$VER-$REL.tgz xsedesig@$REPO:$REPO_SOFTWARE/$REPO_SUBDIR/
scp -p README.md xsedesig@$REPO:$REPO_SOFTWARE/$REPO_SUBDIR/
scp -p README-xsede-user-mapfile xsedesig@$REPO:$REPO_SOFTWARE/$REPO_SUBDIR/
scp -p INSTALL xsedesig@$REPO:$REPO_SOFTWARE/$REPO_SUBDIR/

ssh -l xsedesig  $REPO "cd $REPO_SOFTWARE; rm latest; ln -s $REPO_SUBDIR latest"
ssh -l xsedesig  $REPO "cd $REPO_SOFTWARE; ln -fs latest/INSTALL* ./"
