#!/bin/sh -x

if [ ! -e VERSION ]; then
  echo "You may not be in the right place to run upload"
  echo "Please run from the root of the package"
  exit 1
fi

PKG=access-oauth-mapfile
export VER=$(cat VERSION)
export REL=$(cat RELEASE)
RPMDIR=/home/navarro/rpmbuild/RPMS/noarch
RPMFILE=$RPMDIR/$PKG-$VER-$REL.noarch.rpm
echo "RPMFILE = $RPMFILE"

if [ "$1" = "X86" ]; then
  echo "Building x86_64"
  CURRENTDIR=`pwd`
  echo $CURRENTDIR
  mkdir -p $CURRENTDIR/build/bdist.linux_x86_64/rpm/
  rpmbuild --define "_prefix /usr" --define "_arch x86_64" --define "_topdir $CURRENTDIR/build/bdist.linux_x86_64/rpm" --bb --target x86_64-redhat-linux --clean $PKG.spec --verbose
  mkdir dist
  cp $CURRENTDIR/build/bdist.linux_x86_64/rpm/RPMS/noarch/$RPMFILE ./dist
else
  echo "Building noarch"
  rpmbuild --target noarch -bb $PKG.spec --verbose
fi