#!/bin/bash

PKG=access-oauth-mapfile
VER=$(cat VERSION)
REL=$(cat RELEASE)

HERE=`pwd`
PACKAGES=$HERE/tmp_packages
echo "** BUILDING $PKG-$VER-$REL packages in $PACKAGES **"

./sbin/build-tars || exit 1

cd ./tmp_build/
./$PKG-$VER/sbin/build-rpms

cd $HERE

rm -fr $PACKAGES
mkdir $PACKAGES
cp -p tmp_build/tmp_rpm/$PKG_rpmtopdir/RPMS/noarch/$PKG-$VER-$REL.noarch.rpm $PACKAGES/
cp -p tmp_build/tmp_rpm/$PKG_rpmtopdir/SRPMS/$PKG-$VER-$REL.src.rpm $PACKAGES/
cp -p tmp_build/$PKG-$VER-$REL.tgz $PACKAGES/
(cd $PACKAGES;tar --strip-components 2 -xzf $PKG-$VER-$REL.tgz )

echo "** Results in $PACKAGES:"
(cd $PACKAGES; find ./* -ls)
